baseurl = "https://kylinyu.win/"
languageCode = "zh-tw"
title = "錢麟的墨冊"
theme = "hugo-win-bs-theme"
preserveTaxonomyNames = true
paginate = 3

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
keywords             = ["錢麟的墨冊", "kylinwin", "win", "Blog", "技術筆記", "front"]
description          = "錢麟的墨冊 墨冊 技術筆記 生活記事 旅遊日誌 筆墨日積終將成冊，知識月累便可結果"

categoriesByCount    = true
includeReadingTime   = false
loadFavicon          = true

google_analytics = "UA-36878065-5"
google_adsense = "ca-pub-2289914248932186"
disqus = "https-kylinyu-win"
google_webmaster = ""
bing_webmaster = ""
alexa = ""
twitter = "https://www.twitter.com/nraboy"
googleplus = ""
linkedin = ""
youtube = ""
paypal = ""

[[menu.header]]
    name = "所有文章"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.header]]
    name = "分類"
    url = "/categories"
    weight = 2
    identifier = "fa fa-book"

[[menu.header]]
    name = "關於我"
    url = "/about"
    identifier = "fa fa-user"
    weight = 3
