baseurl = "https://kylinyu.win/"
languageCode = "zh-tw"
title = "錢麟的墨冊"
theme = "readable"
preserveTaxonomyNames = true
paginate = 5

[permalinks]
    post    = "/:filename"
    page    = "/:filename"
    travel  = "/:filename"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    author               = "Win"
    blog_categories      = ["技術", "生活"]
    keywords             = ["錢麟的墨冊", "kylinwin", "win", "Blog", "技術筆記", "front"]
    description          = "錢麟的墨冊 墨冊 技術筆記 生活記事 旅遊日誌 筆墨日積終將成冊，知識月累便可結果"
    footer_description   = "技術筆記 x 生活記事 x 旅遊日誌。筆墨日積終將成冊，知識月累便可結果"
    categoriesByCount    = true
    loadFavicon          = true

    google_analytics = "UA-36878065-5"
    disqus = "https-kylinyu-win"

[social]
    github          = "kylinfish"
    flickr          = "kylinyu"
    linkedin        = "win-yu-0537717b"
    email           = "kylinfish@gmail.tw"
    twitter         = "kylinwin"

[[menu.header]]
    name = "所有文章"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.header]]
    name = "分類"
    url = "/categories"
    weight = 2
    identifier = "fa fa-book"

[[menu.header]]
    name = "關於我"
    url = "/about"
    identifier = "fa fa-user"
    weight = 3
